package gov.fcc.wrv.model.xsd;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Wed Sep 15 11:58:02 EDT 2010  
 */

public interface BiddingDashboardServicePortType extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://webservice.wrv.fcc.gov}sendTestEvent   */

  public void sendTestEvent(gov.fcc.wrv.model.WrvEvent in0) throws java.rmi.RemoteException;
    public void sendTestEventAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.fcc.wrv.model.WrvEvent in0) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://webservice.wrv.fcc.gov}sendEvent   */

  public void sendEvent(gov.fcc.wrv.model.WrvEvent in0) throws java.rmi.RemoteException;
    public void sendEventAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.fcc.wrv.model.WrvEvent in0) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://webservice.wrv.fcc.gov}verifyWS   */

  public void verifyWS() throws java.rmi.RemoteException;
    public void verifyWSAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
  
}