package gov.fcc.wrv.model.xsd;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Wed Sep 15 11:58:02 EDT 2010  
 */

public interface BiddingDashboardService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: BiddingDashboardServiceHttpPort  
     // Port Type: BiddingDashboardServicePortType   
     //***********************************
     
  /**
   * returns BiddingDashboardServiceHttpPort port in this service 
   */
  gov.fcc.wrv.model.xsd.BiddingDashboardServicePortType getBiddingDashboardServiceHttpPort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getBiddingDashboardServiceHttpPort(byte[] username, byte[] password);
   */
  gov.fcc.wrv.model.xsd.BiddingDashboardServicePortType getBiddingDashboardServiceHttpPort(String username, String password) throws javax.xml.rpc.ServiceException;

  gov.fcc.wrv.model.xsd.BiddingDashboardServicePortType getBiddingDashboardServiceHttpPort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }